# Generated by Django 4.0 on 2021-12-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoary',
            new_name='Category',
        ),
    ]
